# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'topic6.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1291, 871)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1291, 881))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.398091, y1:0.358, x2:0.806818, y2:0.778, stop:0.153409 rgba(255, 147, 206, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setGeometry(QtCore.QRect(50, 50, 141, 91))
        self.label_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 85, 255);\n"
"font: 25pt \"MV Boli\";\n"
"border-radius:10px;\n"
"border: 2px solid pink;\n"
"")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(200, 70, 161, 51))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 24pt \"MV Boli\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(510, 60, 561, 71))
        self.label_3.setStyleSheet("font: 24pt \"MV Boli\";\n"
"text-decoration: underline;\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.lesson11 = QtWidgets.QPushButton(self.widget)
        self.lesson11.setGeometry(QtCore.QRect(100, 250, 761, 121))
        self.lesson11.setStyleSheet("font: 24pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border: 4px solid #ffffff;\n"
"border-radius: 10px;")
        self.lesson11.setObjectName("lesson11")
        self.lesson12 = QtWidgets.QPushButton(self.widget)
        self.lesson12.setGeometry(QtCore.QRect(100, 490, 761, 111))
        self.lesson12.setStyleSheet("font: 24pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border: 4px solid #ffffff;\n"
"border-radius: 10px;")
        self.lesson12.setObjectName("lesson12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "hometp6"))
        self.label_1.setText(_translate("MainWindow", "Topic 6"))
        self.label_2.setText(_translate("MainWindow", "やすみのひ"))
        self.label_3.setText(_translate("MainWindow", "Yasumi no hi 1 / Holidays and Days off 1"))
        self.lesson11.setText(_translate("MainWindow", "Lesson 11: What\'s your hobby?"))
        self.lesson12.setText(_translate("MainWindow", "Lesson 12:  Shall we go together?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
